name: Publish packages

on:
    push:
        branches: [ V6-master ]
        paths: [ '.github/publish.txt' ]

    workflow_dispatch:

jobs:
    publish-windows-package:
        runs-on: windows-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up Python 3.8.10 amd64
                uses: actions/setup-python@v4
                with:
                    python-version: 3.8.10
                    architecture: x64

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    python -m venv venv
                    venv\Scripts\python -m pip install --upgrade pip wheel setuptools
                    venv\Scripts\python -m pip install -r requirements.txt
                    venv\Scripts\python -m pip install cos-python-sdk-v5
                    venv\Scripts\python -m pip install pyinstaller

            -   name: Build and publish package
                env:
                    SECRETID: ${{ secrets.SECRETID }}
                    SECRETKEY: ${{ secrets.SECRETKEY }}
                run: |
                    venv\Scripts\Activate.ps1
                    venv\Scripts\python run_build.py --type package --upload

    publish-docker:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -   name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
                    
            - name: Get version from publish.txt
              run: |
                VERSION=$(cat .github/publish.txt | sed 's/^v//')
                echo "VERSION=${VERSION}" >> $GITHUB_ENV
                
            -   name: Build and push
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    tags: amiyabot/amiyabot:${{ env.VERSION }}, amiyabot/amiyabot:latest
